# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mfkWWVibF7xrQ9c4t-t8eUG5YhL-7j_
"""

import joblib
import numpy as np
import streamlit as st
import pandas as pd
import tensorflow as tf

model = tf.keras.models.load_model('Ann_model.keras')
preprocessor = joblib.load('preprocessor.pkl')

st.set_page_config(page_title="Anxiety Screener", page_icon="🧠", layout="centered")

st.markdown("""
<style>
.big-title {
    font-size: 36px;
    font-weight: bold;
    color: #1f77b4;
    text-align: center;
    margin-bottom: 10px;
}
.subtitle {
    font-size: 18px;
    color: #4f4f4f;
    text-align: center;
    margin-top: 0px;
}
hr {
    border: none;
    height: 2px;
    background-color: #ddd;
    margin: 20px 0;
}
</style>
<div class="big-title">🧠 Anxiety Assessment for Facebook Users</div>
<div class="subtitle">Your emotional wellness, one step at a time.</div>
<hr>
""", unsafe_allow_html=True)

st.markdown("""
Welcome to your personal **mental wellness check-in**!
This app predicts your **anxiety level** based on responses and a model trained on U.S. college Facebook users.

💬 **Note**: This tool is for **self-awareness only** and not a professional diagnosis.
""")

# --- Input Section ---
with st.expander("👤 Demographic Information", expanded=True):
    sex = st.selectbox("Sex", ["Male", "Female", "Other"])
    age = st.slider("Age", 14, 50, 21)
    race = st.selectbox("Race", ["White", "Black", "Asian", "Hispanic or Latino", "Other"])

with st.expander("🧠 Mental Health History", expanded=True):
    previously_diagnosed_depression = st.radio("Previously diagnosed with depression?", ["Yes", "No"])
    in_therapy = st.radio("Currently in therapy for depression?", ["Yes", "No"])
    attempted_suicide = st.radio("Attempted suicide in the past year?", ["Yes", "No"])

with st.expander("🩺 Physical Health", expanded=True):
    total_health_issues = st.slider("Medical conditions in past 12 months", 0, 10, 1)

with st.expander("💬 Emotional Check-In", expanded=True):
    hopeless = st.slider("Hopeless feelings", 0, 4, 2, help="0=Never, 4=Always")
    very_sad = st.slider("Very sad feelings", 0, 4, 2)
    overwhelmed = st.slider("Overwhelmed feelings", 0, 4, 2)
    exhausted = st.slider("Emotionally exhausted", 0, 4, 2)
    depressed_function = st.slider("Depression made it hard to function", 0, 4, 2)

with st.expander("📊 Depression Severity Score (PHQ-9)", expanded=True):
    depression_score = st.slider("PHQ-9 Score", 0, 27, 10, help="0-4=Minimal, 5-9=Mild, 10-14=Moderate, 15-19=Moderately Severe, 20-27=Severe")

# --- Prepare Input for Model ---
input_dict = {
    'sex': [sex],
    'Age': [age],
    'Race': [race],
    'Previously_Diagnosed_Depression': [1 if previously_diagnosed_depression == "Yes" else 0],
    'Total_Health_Issues_Score': [total_health_issues],
    'In_Therapy_for_Depression': [1 if in_therapy == "Yes" else 0],
    'Hopeless': [hopeless],
    'Very sad': [very_sad],
    'Depression_Severity_Score': [depression_score],
    'Overwhelmed': [overwhelmed],
    'Exhausted (not physical)': [exhausted],
    'Depressed - hard to function': [depressed_function],
    'Attempted suicide': [1 if attempted_suicide == "Yes" else 0]
}
user_input_df = pd.DataFrame(input_dict)

if st.button("🔍 Assess My Anxiety Level"):
    user_input_encoded = preprocessor.transform(user_input_df)

    # Get predicted probability from ANN model
    prediction_proba = model.predict(user_input_encoded)[0][0]
    prediction = int(prediction_proba > 0.5)

    if prediction == 0:
        st.success("✅ Your anxiety level is assessed as **Minimal or No Anxiety**.")
        st.info("It's good to maintain your well-being with regular self-care and social support.")
    else:
        st.warning("⚠️-🚨Your anxiety level is assessed as **Moderate to Severe**.")
        st.write("Consider consulting a mental health professional or counselor for further evaluation and support.")

    st.write(f"Confidence in this assessment: **{prediction_proba:.2%}**")

import streamlit as st

st.header("Frequently Asked Questions (FAQ) and Information")

with st.expander("What is Anxiety?"):
    st.write("""
    Anxiety is a natural response to stress or danger, characterized by feelings of worry, nervousness, or fear.
    It can become a disorder when these feelings are excessive, persistent, and interfere with daily life.
    """)

with st.expander("Common Symptoms of Anxiety"):
    st.write("""
    - Restlessness or feeling on edge
    - Increased heart rate
    - Rapid breathing
    - Difficulty concentrating
    - Sleep disturbances
    - Muscle tension
    - Avoidance of anxiety-provoking situations
    """)

with st.expander("When to Seek Professional Help?"):
    st.write("""
    If anxiety symptoms are severe, persistent, or impacting your ability to function in daily activities,
    it’s important to consult a healthcare professional for assessment and support.
    """)

with st.expander("Self-Help Tips for Managing Anxiety"):
    st.write("""
    - Practice relaxation techniques like deep breathing, meditation, or yoga
    - Maintain a healthy lifestyle with regular exercise and balanced diet
    - Limit caffeine and alcohol consumption
    - Connect with supportive friends or family
    - Break tasks into smaller steps to reduce overwhelm
    - Seek professional help if needed
    """)

with st.expander("Resources"):
    st.markdown("""
    - [Substance Abuse and Mental Health Services Administration](https://www.samhsa.gov/mental-health/what-is-mental-health/conditions/anxiety)
    - [National Institute of Mental Health (NIMH)](https://www.nimh.nih.gov/health/topics/anxiety-disorders)
    - [MentalHealth.gov](https://www.mentalhealth.gov)
    - [Frequently Asked Questions about Anxiety](https://bbrfoundation.org/faq/frequently-asked-questions-about-anxiety)
    - [Crisis Text Line](https://www.crisistextline.org) — Text HOME to 741741
    """)